export const data = [
  {
    id: 1,
    name: "John Doe",
    email: "john@example.com",
    role: "Admin",
    status: "Active",
    lastLogin: "2024-01-15",
    orders: 23,
    revenue: "$2,340",
  },
  {
    id: 2,
    name: "Jane Smith",
    email: "jane@example.com",
    role: "User",
    status: "Active",
    lastLogin: "2024-01-14",
    orders: 15,
    revenue: "$1,890",
  },
  {
    id: 3,
    name: "Mike Johnson",
    email: "mike@example.com",
    role: "Editor",
    status: "Inactive",
    lastLogin: "2024-01-10",
    orders: 8,
    revenue: "$560",
  },
  {
    id: 4,
    name: "Sarah Wilson",
    email: "sarah@example.com",
    role: "User",
    status: "Pending",
    lastLogin: "Never",
    orders: 0,
    revenue: "$0",
  },
  {
    id: 5,
    name: "David Brown",
    email: "david@example.com",
    role: "User",
    status: "Active",
    lastLogin: "2024-01-15",
    orders: 31,
    revenue: "$3,120",
  },
  {
    id: 6,
    name: "Lisa Anderson",
    email: "lisa@example.com",
    role: "Editor",
    status: "Active",
    lastLogin: "2024-01-13",
    orders: 12,
    revenue: "$1,200",
  },
  {
    id: 7,
    name: "Tom Wilson",
    email: "tom@example.com",
    role: "User",
    status: "Active",
    lastLogin: "2024-01-12",
    orders: 7,
    revenue: "$420",
  },
  {
    id: 8,
    name: "Emma Davis",
    email: "emma@example.com",
    role: "Admin",
    status: "Active",
    lastLogin: "2024-01-15",
    orders: 45,
    revenue: "$4,500",
  },
];

export const columns = [
  { key: "name", label: "Name", sortable: true },
  { key: "email", label: "Email", sortable: true },
  { key: "role", label: "Role", sortable: true },
  { key: "status", label: "Status", sortable: true },
  { key: "lastLogin", label: "Last Login", sortable: true },
  { key: "orders", label: "Orders", sortable: true },
  { key: "revenue", label: "Revenue", sortable: true },
  { key: "actions", label: "Actions", sortable: false },
];
